// STEP 8: replay. Two tiers, never conflated (PRD G7/G8, DECISIONS F11):
//
//  EVIDENCE TIER: the case's stored events are re-fed through the CURRENT ingest -> evidence tracker -> extractor -> gate, on a
//    virtual clock, in a throwaway replay-mode database. Nothing in it is random or wall-clock dependent, so the verdict AND the
//    stored diff are byte-identical run to run. This is the ONLY tier the word "deterministic" applies to.
//  AUDIO TIER: the stored PCM is streamed at 1x through a fresh live-agent session (server/src/replay-audio.ts). The managed
//    LLM is not seedable, so it is run k times and reported as "k/3 passed"; it is never called deterministic here or anywhere.
//
// What a replay asks (and does not ask): "does the CURRENT build still handle this recorded call correctly?"
//   * with an expected state (a repair that RESOLVED): the recorded call is judged against what the customer validated. A call
//     that would have produced a different line than expected must be HELD; a call that matches it must be ALLOWED.
//   * without one (escalated / unresolved / no repair): the only claim is the fail-closed one, "a held call stays held".
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { TallyEvent } from '@tally/contract';
import { initDatabase } from '@tally/db';
import { computeTotalCents } from '@tally/contract';
import { FakeClock } from './clock.js';
import { checkSpokenDrift } from './drift.js';
import { Store, type CommitRequest, type ReplayRunRow } from './committer.js';
import { EvidenceTracker } from './evidence.js';
import { Gate, type GateOptions } from './gate.js';
import { Ingest } from './ingest.js';
import { applyTool, type OrderState } from './order.js';
import type { AllowDecision } from './decision.js';

/** Tally's own outputs: regenerated by the current build during a replay, never replayed */
const TALLY_OUTPUT_KINDS: ReadonlySet<string> = new Set(['repair', 'case', 'gate_waiting', 'verdict', 'order']);

export type ReplayResult = 'pass' | 'fail';
export type Tier = 'evidence' | 'audio';

/** JSON with recursively sorted keys: the byte-identical serialisation the determinism claim is made about. */
export function stableStringify(v: unknown): string {
  const norm = (x: unknown): unknown => Array.isArray(x) ? x.map(norm) : x && typeof x === 'object' ? Object.fromEntries(Object.entries(x as Record<string, unknown>).filter(([, y]) => y !== undefined).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)).map(([k, y]) => [k, norm(y)])) : x;
  return JSON.stringify(norm(v));
}

const canonLine = (l: { item_id: string; quantity: number; modifiers: readonly string[] }) => ({ item_id: l.item_id, quantity: l.quantity, modifiers: [...l.modifiers].sort() });
export const canonLines = (s: Pick<OrderState, 'lines'>) => [...s.lines].map(canonLine).sort((a, b) => (a.item_id < b.item_id ? -1 : 1));
const sameLines = (a: Pick<OrderState, 'lines'>, b: Pick<OrderState, 'lines'>) => stableStringify(canonLines(a)) === stableStringify(canonLines(b));

export interface Expected { state: OrderState; total_cents?: number }

/** What the current gate SHOULD do with the recorded call. Pure. */
export function desiredOutcome(before: OrderState, call: { tool: string; args: Record<string, unknown> }, expected: Expected | null, pattern_key = ''): { desired: 'ALLOW' | 'HOLD'; basis: 'expected_state' | 'held_must_stay_held' | 'evidence_unavailable' } {
  // Holds caused by MISSING evidence (stream down, wait expired, nothing finalised) were right whatever the customer later confirmed:
  // the same stored evidence must keep producing a HOLD. Otherwise an outage case would fail forever and could never be fixed.
  if (['stream_down', 'evidence_timeout', 'no_evidence'].includes(pattern_key.split('|')[2] ?? '')) return { desired: 'HOLD', basis: 'evidence_unavailable' };
  if (!expected) return { desired: 'HOLD', basis: 'held_must_stay_held' };
  if (call.tool === 'confirm_order') return { desired: sameLines(before, expected.state) ? 'ALLOW' : 'HOLD', basis: 'expected_state' };
  const item = call.args.item_id as string | undefined;
  const lineOf = (s: OrderState) => canonLines(s).find((l) => l.item_id === item);
  const proj = applyTool(before, call.tool, call.args);
  // an exact repeat of committed state (NO_CHANGE) leaves the order as it is: judge that line
  const after = proj.ok ? proj.state : proj.error_code === 'NO_CHANGE' ? before : undefined;
  if (!after) return { desired: 'HOLD', basis: 'expected_state' };
  return { desired: stableStringify(lineOf(after)) === stableStringify(lineOf(expected.state)) ? 'ALLOW' : 'HOLD', basis: 'expected_state' };
}

export interface EvidenceReplayOptions {
  /** the build under test: gate parameters and the fault-injection seams (a deliberately broken build must FAIL) */
  gate?: Partial<Pick<GateOptions, 'evidenceWaitMaxMs' | 'minWordConfidence' | 'extract' | 'pollMs'>> & { commit?: (a: AllowDecision, r: CommitRequest) => ReturnType<NonNullable<GateOptions['commit']>> };
  sttStallMs?: number;
  /** test seam: the spoken-drift checker under test (a deliberately broken one must FAIL a drift case) */
  drift?: typeof checkSpokenDrift;
  /** label recorded on the run (Step 9 versions configs; the evidence tier tests the gating BUILD, not the LLM) */
  configVersion?: string;
  /** write the run to replay_runs (default true) */
  persist?: boolean;
  /** groups this run with the rest of a suite (Step 9) */
  suiteRunId?: string;
}

export interface EvidenceReplayReport {
  case_id: string; tier: 'evidence'; result: ReplayResult; label: string; diff: Record<string, unknown>; diff_json: string; duration_ms: number; run_id?: string;
}

export class ReplayError extends Error { constructor(readonly code: 'case_not_found' | 'bad_snapshot' | 'no_expected_state' | 'no_audio' | 'not_a_replay', msg: string) { super(msg); } }

interface Snapshot {
  version: number; aai_call_id: string;
  call: { tool: string; args: Record<string, unknown>; t_received_ms: number | null };
  verdict: { code: string };
  order_before: OrderState | null;
  events: (TallyEvent & { t_ms: number })[];
}

export async function replayEvidence(live: Store, caseId: string, opts: EvidenceReplayOptions = {}): Promise<EvidenceReplayReport> {
  const started = performance.now();
  const c = live.getCase(caseId);
  if (!c) throw new ReplayError('case_not_found', `no case ${caseId}`);
  let snap: Snapshot;
  try { snap = JSON.parse(c.event_snapshot_json) as Snapshot; } catch { throw new ReplayError('bad_snapshot', 'snapshot is not valid JSON'); }
  if (snap.version !== 1 || !snap.call || !Array.isArray(snap.events) || !snap.order_before) throw new ReplayError('bad_snapshot', 'unsupported snapshot');

  // STEP 10: a spoken-drift case has no tool call to re-gate. What must still hold is that the CURRENT drift check detects the same
  // disagreement between what the agent said and the order it said it against. Pure and deterministic; no database needed.
  if (snap.call.tool === 'agent_speech') {
    const args = snap.call.args as { text?: string; item_id?: string | null };
    const found = (opts.drift ?? checkSpokenDrift)(String(args.text ?? ''), { lines: snap.order_before.lines, total_cents: computeTotalCents(snap.order_before.lines) });
    const same = found.some((f) => f.code === snap.verdict.code && (f.item_id ?? null) === (args.item_id ?? null));
    const result: ReplayResult = same ? 'pass' : 'fail';
    const diff: Record<string, unknown> = {
      schema: 1, tier: 'evidence', basis: 'drift_detection', desired: 'DETECT', reason: same ? 'still_detected' : 'DRIFT_NOT_DETECTED', result,
      case: { pattern_key: c.pattern_key, original_code: snap.verdict.code, resolution: c.resolution },
      call: { tool: 'agent_speech', text: args.text ?? null, item_id: args.item_id ?? null },
      actual: { findings: found.map((f) => ({ code: f.code, item_id: f.item_id ?? null })) }, order_before: canonLines(snap.order_before),
    };
    const diff_json = stableStringify(diff);
    const duration_ms = performance.now() - started;
    const run_id = opts.persist === false ? undefined : live.recordReplayRun({ case_id: c.id, config_version: opts.configVersion ?? 'current', result, tier: 'evidence', attempt_k: 1, actual_state_json: null, diff_json, suite_run_id: opts.suiteRunId ?? null, duration_ms });
    return { case_id: c.id, tier: 'evidence', result, label: `${result.toUpperCase()} (deterministic)`, diff, diff_json, duration_ms, run_id };
  }

  // A throwaway replay-mode database: the live database is never touched by an evidence replay (except the run record below).
  const dir = mkdtempSync(join(tmpdir(), 'tally-replay-'));
  const path = join(dir, 'replay.sqlite');
  initDatabase(path);
  const rs = new Store(path);
  try {
    const sid = `replay_${c.id}`;
    rs.createSession({ id: sid, mode: 'replay', config_version: opts.configVersion ?? 'current' });
    rs.openOrder(sid);
    rs.seedReplayOrder(sid, snap.order_before);

    const clock = new FakeClock();
    const tracker = new EvidenceTracker({ sttStallMs: opts.sttStallMs ?? 2500 });
    const ingest = new Ingest(rs);
    // Tally's own outputs (repair / case) are regenerated by the current build, never replayed
    const events = snap.events.filter((e) => !TALLY_OUTPUT_KINDS.has(e.kind)).map((e) => ({ ...e, session_id: sid }) as TallyEvent);
    const emit = (e: TallyEvent) => { ingest.push(e); tracker.ingest(e); };          // the SAME two sinks the live runtime feeds (SessionRuntime.emit)
    const tCall = snap.call.t_received_ms ?? (events.length ? events[events.length - 1]!.t_ms : 0);
    for (const e of events) {
      if (e.t_ms <= tCall) { clock.advance(Math.max(0, e.t_ms - clock.now())); emit(e); }
      else clock.at(e.t_ms, () => emit(e));                                          // arrived while the gate was waiting: delivered at its original time
    }
    clock.advance(Math.max(0, tCall - clock.now()));

    const gate = new Gate({ store: rs, evidenceFor: () => tracker, clock, ...opts.gate });
    const res = await gate.submit({ session_id: sid, aai_call_id: snap.aai_call_id, tool: snap.call.tool, args: snap.call.args, received_t_ms: tCall });
    const afterRow = rs.getOrder(sid);
    if (!afterRow) throw new ReplayError('bad_snapshot', 'replay order missing');

    const expected: Expected | null = c.expected_state_json ? (JSON.parse(c.expected_state_json) as Expected) : null;
    const { desired, basis } = desiredOutcome(snap.order_before, snap.call, expected, c.pattern_key);
    const heldOrderUnchanged = sameLines(afterRow.state, snap.order_before) && afterRow.state.status === snap.order_before.status;
    let result: ReplayResult; let reason: string;
    if (desired === 'HOLD') {
      if (res.verdict === 'HOLD' && heldOrderUnchanged) { result = 'pass'; reason = 'still_held'; }
      else { result = 'fail'; reason = res.verdict === 'ALLOW' ? 'SAFETY_REGRESSION_now_allowed_but_must_be_held' : 'held_but_order_changed'; }
    } else if (res.verdict === 'ALLOW') { result = 'pass'; reason = 'allowed_as_expected'; }
    else { result = 'fail'; reason = 'held_but_the_recorded_call_was_correct'; }

    const diff: Record<string, unknown> = {
      schema: 1, tier: 'evidence', basis, desired, reason, result,
      case: { pattern_key: c.pattern_key, original_code: snap.verdict.code, resolution: c.resolution },
      call: { tool: snap.call.tool, args: snap.call.args },
      actual: { verdict: res.verdict, code: res.verdict === 'HOLD' ? res.code : null, noop: res.verdict === 'ALLOW' ? !!res.noop : null, waited_ms: res.waited_ms ?? null },
      code_changed: res.verdict === 'HOLD' ? res.code !== snap.verdict.code : null,
      order_before: canonLines(snap.order_before), order_after: canonLines(afterRow.state),
      expected_lines: expected ? canonLines(expected.state) : null,
    };
    const diff_json = stableStringify(diff);
    const duration_ms = performance.now() - started;
    const label = `${result.toUpperCase()} (deterministic)`;
    let run_id: string | undefined;
    if (opts.persist !== false) {
      run_id = live.recordReplayRun({ case_id: c.id, config_version: opts.configVersion ?? 'current', result, tier: 'evidence', attempt_k: 1, actual_state_json: stableStringify({ lines: canonLines(afterRow.state), status: afterRow.state.status }), diff_json, suite_run_id: opts.suiteRunId ?? null, duration_ms });
    }
    return { case_id: c.id, tier: 'evidence', result, label, diff, diff_json, duration_ms, run_id };
  } finally {
    rs.close();
    try { rmSync(dir, { recursive: true, force: true }); } catch { /* temp cleanup is best effort */ }
  }
}

// ---- audio tier: pure pieces (the network runner lives in server/src/replay-audio.ts) ----

/** One audio-tier attempt: the FINAL order vs the expected state. The agent's speech is never consulted (rule 3). */
export function judgeAudioRun(finalOrder: { lines: OrderState['lines'] } | undefined, expected: Expected): { result: ReplayResult; diff: Record<string, unknown> } {
  const actual = finalOrder ? canonLines(finalOrder) : null;
  const want = canonLines(expected.state);
  const ok = actual !== null && stableStringify(actual) === stableStringify(want);
  return { result: ok ? 'pass' : 'fail', diff: { tier: 'audio', expected_lines: want, actual_lines: actual, equal: ok } };
}

/** The wording rule: audio-tier results are "k/N passed" and ALL must pass; nothing here ever says "deterministic". */
export function describeReplay(tier: Tier, results: readonly ReplayResult[]): { passed: number; k: number; overall: ReplayResult; label: string } {
  const passed = results.filter((r) => r === 'pass').length;
  const k = results.length;
  if (tier === 'evidence') {
    const overall: ReplayResult = k === 1 && passed === 1 ? 'pass' : 'fail';
    return { passed, k, overall, label: `${overall.toUpperCase()} (deterministic)` };
  }
  const overall: ReplayResult = k > 0 && passed === k ? 'pass' : 'fail';
  return { passed, k, overall, label: overall === 'pass' ? `${passed}/${k} passed` : `${passed}/${k} passed: FAIL` };
}

export type { ReplayRunRow };
